### ISSUE TITLE
Context cannot be read from non-existent files

### ISSUE THREAD

**Issue by jcrd** [Yilin-Yang/vim-markbar#11] opened 2018-12-15 19:45 UTC
When displaying the context of special marks for previously edited files (`` `0 ``, `` `1 ``, etc.), non-existent files will show `[buffer line read failed]`. This is also true of `term://` buffers that have exited.

**Comment by Yilin-Yang** [comment] 2018-12-16 08:20
Howdy!

As you've described it, this sounds like intended behavior; `[buffer line read failed]` is the "context" that's supposed to be returned when the requested file/buffer no longer exists. Are you asking for vim-markbar to handle this differently (e.g. by not showing the `~` lines before/after `[buffer ... failed]`)?

Best,
Yilin

**Comment by jcrd** [comment] 2018-12-16 19:41
I was expecting a specific error message, or like you suggested, different handling of its presentation to make it clear that this error is anticipated by vim-markbar. Although, the message is fairly descriptive as is, so this may just come down to cosmetics.

**Comment by Yilin-Yang** [comment] 2018-12-21 04:01
I understand; no worries! I'm sorry to say that this isn't a high priority for me, since this is more a matter of personal taste than functionality. I'll mark this as `wontfix` for now, but please don't be afraid to report issues or request features in the future!

**Closed by Yilin-Yang** 2018-12-21 04:01 UTC
