### ISSUE TITLE
persist deleted marks accross vim/neovim sessions

### ISSUE THREAD

**Issue by RonanMacF** [Yilin-Yang/vim-markbar#24] opened 2020-09-03 19:55 UTC
Hi, when deleting marks it stays hidden during the current neovim session. However, once I exit and return the deleted marks reappear, I imagine because we are not editing the shada file at all. It would be nice if vim-markbar did this as it would provide a very user friendly way to remove marks on the fly as we see them.

**Comment by Yilin-Yang** [comment] 2022-04-28 00:38
Closing as a duplicate of #20, but adding this feature is now on the roadmap.

**Closed by Yilin-Yang** 2022-04-28 00:38 UTC
Labels: duplicate
